@base_url = http://localhost:7072/api
@user_uuid = b4cf95b0-6b7e-4d64-b65b-b708f8c55b57
@jwt = eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwidHlwIjoiSldUIiwiY3R5IjoiSldUIn0.r0NJzDDuBQq-6-f45nD65mzIEIJ2OtWtYyfBkKdY2I4FvGicAMhM_eufk0M0yE41srOsbWBgILEN_Trp-GRPQApTJGapLBWV.63If7tRaTdODITZRXwumXQ.m-hZX7tOMvcEV8ScpcuCJ7b3CJo30MTaMZWmK1ZcAlaitdKX1l96LuUBFDr0OLm2ytXSt7ZgZ2tFJbZ_1m21y8btfC0deI0R1apa89hHeqK09D_DFG2yZ5f-eg0htvM_vIpd4bHWtUBgAExnp03TlT8ZYpHNlcXbS-btGghTNzfe_Otp167ZWX1S2fTFxrCZ8R00NCSWNZ5BUP0YsiKubajhk6nFTXuCXYznGL9CInHQ6wW-ufJ1GP0YVEhSaashFcASxT_r6ljG7Ff9gbtOmSarCGeY8w_E6Ah3S13gTiGcsijFUGVAgjSjMK-RQx29OYNim0o7RJ2jlFc0NG_PaqogjmyZsMYa0ND4TijQGjccY-zBY8pPomM25WLvcLWu-V3MMIk3oTT_kkCkZXrsjYn94vF_AkrzcMAVz6ymrz-BsI12cUIWyQ5dIgXLBk8UUrBWkoPIvSjHnn9KIgADg5isj6gUxbB_UJrxeQ-ipyoP7rSAnRp6ZjFztBlQSB0FrHiE-5ikL5Z2gAS6XSqE0RQKHBLxFIGAXLVT7hsJ63asXGVutZRFnatMGaUNo7hT.6q5xptcQl7Di94vUIqWgPWDXBjRYtEDIl7uvjPTAIh8

GET {{base_url}}/v1/user/{{user_uuid}} HTTP/1.1
Authorization: Bearer {{jwt}}
