@base_url = http://localhost:7072

### Password grant login
POST {{base_url}}/api/oauth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=tero.testaaja@goodlife.technology&password=SalainenSanaSala123&scope=


### Login page
GET {{base_url}}/login?lang=fi HTTP/1.1


### Authorization code login
